OBJS-$(BV_CONFIG_HISAVI_INDEV)              += his3515/hisavi.o
OBJS-$(BV_CONFIG_HISAVE_INDEV)              += his3515/hisave.o
OBJS-$(BV_CONFIG_HISAVO_OUTDEV)             += his3515/hisavo.o
OBJS-$(BV_CONFIG_HISAVD_OUTDEV)             += his3515/hisavd.o
