all:
	gcc -Wall open_input.c ../stream.c -o test -I ../ -I ../../ -I /home/albert/x86/ffmpeg2/include/ -L /home/albert/x86/ffmpeg2/lib/ -lavformat -lavdevice -lavutil -lavcodec -L /home/albert/bvlive/3rdparty/onvif/lib/ -lonvifc
